myFood = input("Name a food > ")
myPlant = input("Name a type of plant > ")
myCooking = input("Name a method of cooking > ")
myBurned = input("What word describes burned food? > ")
myItem = input("Name a DIY item > ")
print("So you want , myFood, with , myPlant, on a bed of , myItem, ?")
